// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnX0Hbngik4xljHCe5tDmsuekZ2cOSei4',
    appId: '1:628184017518:web:51d9c21ab494629499547f',
    messagingSenderId: '628184017518',
    projectId: 'fast-danggn-app',
    authDomain: 'fast-danggn-app.firebaseapp.com',
    storageBucket: 'fast-danggn-app.appspot.com',
    measurementId: 'G-M65BE68EYL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwy7UulNG3-rLVGLOOT1xAEzK18o2XiDo',
    appId: '1:628184017518:android:d1689026cad7f86099547f',
    messagingSenderId: '628184017518',
    projectId: 'fast-danggn-app',
    storageBucket: 'fast-danggn-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcrkTaeUZImPYJ2rCEDB8LDYnxBNzZ6DU',
    appId: '1:628184017518:ios:8038b91db6baaa9f99547f',
    messagingSenderId: '628184017518',
    projectId: 'fast-danggn-app',
    storageBucket: 'fast-danggn-app.appspot.com',
    iosBundleId: 'com.example.fastAppBase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcrkTaeUZImPYJ2rCEDB8LDYnxBNzZ6DU',
    appId: '1:628184017518:ios:8038b91db6baaa9f99547f',
    messagingSenderId: '628184017518',
    projectId: 'fast-danggn-app',
    storageBucket: 'fast-danggn-app.appspot.com',
    iosBundleId: 'com.example.fastAppBase',
  );
}
